name: Publish Python distributions to PYPI

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update version
        run: python get_latest_version.py
      - name: Install deployment dependencies
        if: github.event.pull_request.merged == true
        run: |
          pip install twine
          pip install pexpect
      - name: Package module
        if: github.event.pull_request.merged == true
        run: python setup.py sdist
      - name: Deploy to PYPI
        if: github.event.pull_request.merged == true
        env:
          TWINE_USERNAME: ${{secrets.MYPYPI_UN}}
          TWINE_PASSWORD: ${{secrets.MYPYPI_PD}}
        run: twine upload dist/*
          